export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>TaskboardPro</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.header-nav[_ngcontent-ng-c850304541]{display:flex;justify-content:space-between;align-items:center;padding:1rem 2rem;background-color:#3b82f6;color:#fff;box-shadow:0 4px 8px #0000001a;border-radius:0 0 12px 12px}.header-nav[_ngcontent-ng-c850304541]   .logo[_ngcontent-ng-c850304541]{font-size:1.5rem;font-weight:700;letter-spacing:1px;cursor:default}.nav-links[_ngcontent-ng-c850304541]{display:flex;gap:1.5rem;list-style:none;margin:0;padding:0}.nav-links[_ngcontent-ng-c850304541]   a[_ngcontent-ng-c850304541]{text-decoration:none;color:#fff;font-weight:500;position:relative;transition:color .3s}.nav-links[_ngcontent-ng-c850304541]   a[_ngcontent-ng-c850304541]:hover{color:#dbeafe}.nav-links[_ngcontent-ng-c850304541]   a.active[_ngcontent-ng-c850304541]:after{content:"";position:absolute;bottom:-4px;left:0;width:100%;height:3px;background-color:#facc15;border-radius:2px}@media (max-width: 600px){.header-nav[_ngcontent-ng-c850304541]{flex-direction:column;align-items:flex-start;padding:1rem}.nav-links[_ngcontent-ng-c850304541]{flex-direction:column;gap:1rem;width:100%}.nav-links[_ngcontent-ng-c850304541]   a.active[_ngcontent-ng-c850304541]:after{bottom:0}}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="20.3.15" ngh="1" ng-server-context="ssg"><app-header _nghost-ng-c850304541 ngh="0"><nav _ngcontent-ng-c850304541 class="header-nav"><div _ngcontent-ng-c850304541 class="logo">TaskBoard Pro</div><ul _ngcontent-ng-c850304541 class="nav-links"><li _ngcontent-ng-c850304541><a _ngcontent-ng-c850304541 routerlink="/" routerlinkactive="active" href="/" class jsaction="click:;">Home</a></li><li _ngcontent-ng-c850304541><a _ngcontent-ng-c850304541 routerlink="/tasks" routerlinkactive="active" href="/tasks" class jsaction="click:;">Tasks</a></li><li _ngcontent-ng-c850304541><a _ngcontent-ng-c850304541 routerlink="/tasks/dashboard" routerlinkactive="active" href="/tasks/dashboard" class jsaction="click:;">Dashboard</a></li><li _ngcontent-ng-c850304541><a _ngcontent-ng-c850304541 routerlink="/about" routerlinkactive="active" href="/about" class="active" jsaction="click:;">About</a></li></ul></nav></app-header><router-outlet></router-outlet><app-about-component ngh="0"><p>about-component works!</p></app-about-component><!----></app-root>
<link rel="modulepreload" href="chunk-TDGHQIUL.js"><link rel="modulepreload" href="chunk-VCTWHCQC.js"><script src="main-QI4SMHIE.js" type="module"></script>
<link rel="modulepreload" href="chunk-RZNHTRUF.js">


<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"1":[{"i":"c1820127702","r":1}]}}]}</script></body></html>`;